---
- hosts: clients
  gather_facts: no
  vars_files:
    - "{{ vars_file }}"
  tasks:
    - name: "running install"
      shell: |
        cd ${HOME} ;
        git clone https://github.com/KDahlgren/pdsw19-reprod.git ;
        cd pdsw19-reprod ;
        git checkout popperized ;
        time bash ansible/transforms.sh {{ numosds }} ;
      register: shell_output
    - debug: var=shell_output.stdout_lines
